### ISSUE TITLE
Bug: Скрипт загружается до построения DOM

### ISSUE THREAD

**Issue by SamIvan-ark** [Hexlet/hexlet-correction#201]
### Summary

Скрипт загружается до построения DOM и ломается, когда пытается найти body. 
Исходные скрипты для встраивания ТР:
```
<script src="https://cdn.jsdelivr.net/gh/hexlet/hexlet-correction@main/src/widget/index.js"></script>
<script>
    handleTypoReporter({ authorizationToken: 'MzAyOmQ2ZTI5ZTBhLTRkMmUtNGFlOS05MzQ2LTY4NTFlMzUwY2ZhYQ==',
    workSpaceUrl: 'https://hexlet-correction.herokuapp.com', workSpaceId: '302'})
</script>
```

Проблему решили навешиванием события, что DOM готов:
```
<script src="https://cdn.jsdelivr.net/gh/hexlet/hexlet-correction@main/src/widget/index.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    handleTypoReporter({ authorizationToken: 'MzAyOmQ2ZTI5ZTBhLTRkMmUtNGFlOS05MzQ2LTY4NTFlMzUwY2ZhYQ==',
    workSpaceUrl: 'https://hexlet-correction.herokuapp.com', workSpaceId: '302'})
});
</script>
```

### Reproduction steps

```bash
1. Вставить скрипт в head
2. Открыть консоль
3. Увидеть ошибку, что body === null
```

### Expected result

Элемент тайпорепортера есть на странице

### Actual result

Элемента нет, в консоли ошибка
```
index.js:176 Uncaught TypeError: Cannot read properties of null (reading 'append')
    at generateModal (index.js:176:8)
    at handleTypoReporter (index.js:277:20)
```

### Browsers

Chrome

**Comment by fey** [comment]
@Mari-Krukovskaya можете взять в работу. Тут задача не совсем фронтендовая - она скорее на стыке.
Нужно проверить, что новый сниппет будет ОК работать и поменять код сниппета в шаблоне страницы. Сам шаблон страницы написан на Java, но я думаю, что сможете разобраться

**Comment by fey** [comment]
Актуально и выглядит несложно.

**Comment by fey** [comment]
@amirhraj берите)

**Comment by amirhraj** [comment]
взял в работу

**Comment by fey** [comment]
Задача актуальна.
